### ISSUE TITLE
How to deploy it on K8S?

### ISSUE THREAD

**Issue by pipidaxian** [vital987/vubuntu#24]
Hi, I am learning k8s and want to deploy your app on k8s. Do you have some suggestions for me?

**Comment by vital987** [comment]
To deploy on Kubernetes, create a simple deployment and port-forward (can have better option) the pod port: 
```
apiVersion: v1
kind: Pod
metadata:
  name: vubuntu
spec:
  containers:
  - name: vubuntu
    image: vital987/vubuntu:minimal
    env:
    - name: PORT
      value: "80"
    - name: VNC_TITLE
      value: "Vubuntu"
    - name: VNC_RESOLUTION
      value: "1280x720"
 ---
```
This playbook would work, but you need to port-forward the port using,
```
kubectl port-forward pods/vubuntu 80:80
```
